### PR TITLE
Correcting file name: fr_FR.po -> fr.po

### PR DESCRIPTION
**Pull request by JehoG**

### CODE REVIEW

**Comment by JehoG** [comment]
@yvaucher Can you check this PR?

**Comment by yvaucher** [comment]
@JehoG That seems ok but what is this project?

**Comment by JehoG** [comment]
It's for a project, the translation dosn't work because the file isn't well named.

**Comment by JehoG** [comment]
@yvaucher Sorry, I made an error on this one. Wanted to poke another person.

**Pull request merged**
