### PR TITLE
[ADD] Tests for product_dimensions

### PR DESCRIPTION
**Pull request by JehoG**
Added tests to allows jenkins to pass.
Anyway there was no tests in this module.
@gaultp

### CODE REVIEW

**Comment by JehoG** [comment]
I got told that the copyright were not necessary in **init**.py, is it?
And what do you mean by the missing checks?

**Comment by veloutin** [comment]
the **init**.py file needs to import all the test modules (already done) and list them in checks or fast_suite : http://openerp-server.readthedocs.org/en/latest/05_test_framework.html

in this case you probably want

```
checks = [
    test_product_weight
]
```

**Comment by JehoG** [comment]
I have this message when I add the checks:
"Found deprecated fast_suite or checks attributes in test module openerp.addons.product_dimensions.tests. These have no effect in or after version 8.0." 
So these are only necessary before V8, but good to know for V7.

**Comment by veloutin** [comment]
@JehoG Looks like I'm deprecated! Good to know :cry:

**Pull request closed without merging**
